// src/types/database.ts
// Database types — will be auto-generated by `npx supabase gen types typescript`
// These are placeholder types matching our schema for development

export type OrderStatus = 'pending' | 'confirmed' | 'preparing' | 'ready' | 'delivered' | 'cancelled'
export type SessionStatus = 'active' | 'closed' | 'expired'
export type RoleName = 'super_admin' | 'manager' | 'kitchen' | 'waiter' | 'customer'

export interface Role {
    id: number
    name: RoleName
    description: string | null
}

export interface Restaurant {
    id: string
    owner_id: string | null
    name: string
    slug: string
    logo_url: string | null
    is_active: boolean
    created_at: string
}

export interface User {
    id: string
    restaurant_id: string
    full_name: string
    avatar_url: string | null
    role_id: number
    is_active: boolean
    created_at: string
    updated_at: string
    // Joined fields
    roles?: Role
}

export interface Table {
    id: string
    restaurant_id: string
    label: string
    qr_token: string
    nfc_uid: string | null
    capacity: number | null
    is_active: boolean
    created_at: string
}

export interface MenuCategory {
    id: string
    restaurant_id: string
    name: string
    sort_order: number
    is_visible: boolean
}

export interface MenuItem {
    id: string
    restaurant_id: string
    category_id: string | null
    name: string
    description: string | null
    price: number
    image_url: string | null
    is_available: boolean
    stock_count: number | null
    preparation_min: number | null
    allergens: string[] | null
    tags: string[] | null
    created_at: string
    updated_at: string
    // Joined fields
    menu_categories?: MenuCategory
}

export interface Session {
    id: string
    table_id: string
    restaurant_id: string
    opened_by: string
    session_token: string
    status: SessionStatus
    opened_at: string
    closed_at: string | null
    expires_at: string
    guest_count: number | null
    notes: string | null
    // Joined fields
    tables?: Table
}

export interface Order {
    id: string
    session_id: string
    restaurant_id: string
    customer_note: string | null
    status: OrderStatus
    total_amount: number
    placed_at: string
    confirmed_at: string | null
    ready_at: string | null
    delivered_at: string | null
    // Joined fields
    order_items?: OrderItem[]
    sessions?: Session
}

export interface OrderItem {
    id: string
    order_id: string
    menu_item_id: string
    quantity: number
    unit_price: number
    special_request: string | null
    created_at: string
    // Joined fields
    menu_items?: MenuItem
}

export interface Settings {
    id: string
    restaurant_id: string
    theme: {
        primaryColor: string
        secondaryColor: string
        fontFamily: string
        borderRadius: string
        menuLayout: string
    }
    features: {
        tipsEnabled: boolean
        feedbackEnabled: boolean
        geofenceEnabled: boolean
        geofenceRadiusMeters: number
    }
    business_hours: Record<string, unknown> | null
    updated_at: string
}

// Cart types (client-side only)
export interface CartItem {
    menuItemId: string
    name: string
    price: number
    quantity: number
    specialRequest?: string
    imageUrl?: string
}
